### ISSUE TITLE
Solr 8.11.2 support?

### ISSUE THREAD

**Issue by heathprovost** [bremeld/solr-undertow#39]
Just wondering if this is maybe being looked at... We would very much like to be able to backup/restore to S3 repositories, which was added in 8.10. I tried to get this to work as is, but there is some kind of issue with loading `org.restlet.ext.servlet.ServerServlet` and I have not figure out what it is...

```
12:15:14 - Server unhandled exception during startup 'org.restlet.ext.servlet.ServerServlet'
java.lang.ClassNotFoundException: org.restlet.ext.servlet.ServerServlet
        at java.lang.ClassLoader.findClass(ClassLoader.java:523)
        at uy.kohesive.solr.undertow.ChildFirstClassloader.findClass(CustomClassloader.kt:36)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at uy.kohesive.solr.undertow.ChildFirstClassloader.loadClass(CustomClassloader.kt:22)
        at uy.kohesive.solr.undertow.ChildFirstClassloader.loadClass(CustomClassloader.kt:27)
        at uy.kohesive.solr.undertow.Server.buildSolrServletHandler(SolrUndertow.kt:367)
        at uy.kohesive.solr.undertow.Server.run(SolrUndertow.kt:80)
        at uy.kohesive.solr.undertow.App$Companion.main(App.kt:50)
        at uy.kohesive.solr.undertow.App.main(App.kt)
Server unhandled exception during startup 'org.restlet.ext.servlet.ServerServlet'
```

**Comment by heathprovost** [comment]
So I finally figured it out I think... The versions past 8.7.0 removed the dependency on `org.restlet.ext.servlet` and they no longer even spin up  the `SolrRestApi` servlet at all (it all seems to be handled by the SolrDispatchFilter I think, I dunno but it works without it). 

Anyway, I got it to work with 8.11.2 by just making all that stuff conditional on the Class(es) being successfully loaded... Do you want a PR for it?
